# This is a portable profile that reads from Environment Variables
medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
      schema: public
      threads: 4